routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\CursoController;
use App\Http\Controllers\ContactoController;

Route::get('/', HomeController::class)->name('home');

Route::resource('cursos', CursoController::class);

Route::view('nosotros', 'nosotros')->name('nosotros');

Route::get('contactanos', [ContactoController::class, 'index'])->name('contacto.index');
Route::post('contactanos', [ContactoController::class, 'store'])->name('contacto.store');

app/Models/Curso.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Curso extends Model
{
    use HasFactory;
    
    protected $guarded = [];

    public function getRouteKeyName()
    {
        return 'slug';
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ContactoController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Mail\ContactanosMailable;
use Illuminate\Support\Facades\Mail;

class ContactoController extends Controller
{
    public function index()
    {
        return view('contacto.index');
    }

    public function store(Request $request)
    {
        $request->validate([
            'name'     => 'required',
            'correo'   => 'required|email',
            'mensaje'  => 'required'
        ]);

        $correo = new ContactanosMailable($request->all());
        Mail::to('marco.tiendar@gmail.com')->send($correo);

        return redirect()->route('contacto.index')->with('info', 'Mensaje enviado');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CursoController.php
<?php

namespace App\Http\Controllers;

use App\Models\Curso;
use Illuminate\Http\Request;
use App\Http\Requests\StoreCurso;

class CursoController extends Controller
{
    public function index()
    {
        $cursos = Curso::orderBy('id', 'desc')->paginate();
        return view('cursos.index', compact('cursos'));
    }

    public function create()
    {
        return view('cursos.create');
    }

    public function store(StoreCurso $request)
    {
        $curso = Curso::create($request->all());
        return redirect()->route('cursos.show', $curso);
    }

    public function show(Curso $curso)
    {
        return view('cursos.show', compact('curso'));
    }

    public function edit(Curso $curso)
    {
        return view('cursos.edit', compact('curso'));
    }

    public function update(StoreCurso $request, Curso $curso)
    {
        $curso->update($request->all());
        return redirect()->route('cursos.show', $curso);
    }

    public function destroy(Curso $curso)
    {
        $curso->delete();
        return redirect()->route('cursos.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers; // <- Lugar donde se encuentra el archivo

use Illuminate\Http\Request;

class HomeController extends Controller
{
  /**
   * Ocupamos el método __invoke, cuando queremos que el controlador
   * invoke una única ruta
   */
  public function __invoke()
  {
    return view('home');
  }
}

resources/views/contacto/index.blade.php
@extends('layaouts.layaout')

@section('title', 'Contacto')

@section('content')
	<h1>Déjanos un mensaje</h1>

  <form action="{{ route('contacto.store') }}" method="POST">
    @csrf

    <label>
      Nombre:
      <br>
      <input type="text" name="name">
    </label>
    <br>

    @error('name')
      <p><strong>{{ $message }}</strong></p>
    @enderror

    <label>
      Correo:
      <br>
      <input type="email" name="correo">
    </label>
    <br>

    @error('correo')
      <p><strong>{{ $message }}</strong></p>
    @enderror

    <label>
      Mensaje:
      <br>
      <textarea name="mensaje" rows="5"></textarea>
    </label>

    @error('mensaje')
      <p><strong>{{ $message }}</strong></p>
    @enderror

    <br>
    <button type="submit">Enviar mensaje</button>
  </form>

  @if (session('info'))
    <script>
      alert("{{ session('info') }}");
    </script>
  @endif
@endsection

resources/views/cursos/create.blade.php
@extends('layaouts.layaout')

@section('title', 'Cursos create')

@section('content')
    <h1>En esta página podrás crear un curso</h1>

    <form action="{{ route('cursos.store') }}" method="POST">
        @csrf {{-- Token Csrf --}}

        <label>
            Nombre:
            <br>
            <input type="text" name="name" value="{{ old('name') }}">
        </label>

        @error('name')
            <br>
            <small>*{{ $message }}</small>
            <br>
        @enderror
        
        <br>
        <label>
            Descripción:
            <br>
            <textarea name="descripcion" rows="5">{{ old('descripcion') }}</textarea>
        </label>

        @error('descripcion')
            <br>
            <small>*{{ $message }}</small>
            <br>
        @enderror

        <br>
        <label>
            Categoría:
            <br>
            <input type="text" name="categoria" value="{{ old('descripcion') }}">
        </label>

        @error('categoria')
            <br>
            <small>*{{ $message }}</small>
            <br>
        @enderror

        <br>
        <button type="submit">Enviar formulario</button>
    </form>
@endsection

resources/views/cursos/edit.blade.php
@extends('layaouts.layaout')

@section('title', 'Cursos edit')

@section('content')
    <h1>En esta página podrás editar un curso</h1>

    <form action="{{ route('cursos.update', $curso) }}" method="POST">
        @csrf {{-- Token Csrf --}}
        @method('PUT')

        <label>
        Nombre:
        <br>
        <input type="text" name="name" value="{{ old('name', $curso->name) }}">
        </label>

        @error('name')
        <br>
        <small>*{{ $message }}</small>
        <br>
        @enderror

        <br>
        <label>
        Descripción:
        <br>
        <textarea name="descripcion" rows="5">{{ old('descripcion', $curso->descripcion) }}</textarea>
        </label>

        @error('descripcion')
        <br>
        <small>*{{ $message }}</small>
        <br>
        @enderror

        <br>
        <label>
        Categoría:
        <br>
        <input type="text" name="categoria" value="{{ old('categoria', $curso->categoria) }}">
        </label>

        @error('categoria')
        <br>
        <small>*{{ $message }}</small>
        <br>
        @enderror

        <br>
        <button type="submit">Actualizar formulario</button>
    </form>
@endsection

resources/views/cursos/index.blade.php
@extends('layaouts.layaout')

@section('title', 'Cursos')

@section('content')    
    <h1>Bienvenido a la página principal de cursos</h1>

    <a href="{{ route('cursos.create') }}">Crear un curso</a>
    <ul>
        @foreach ($cursos as $curso)
            <li>
                <a href="{{ route('cursos.show', $curso) }}">{{ $curso->name }}</a>
            </li>
        @endforeach
    </ul>

    {{ $cursos->links() }} {{-- De esta forma paginamos todos los datos de nuestra colección --}}
@endsection

resources/views/cursos/show.blade.php
@extends('layaouts.layaout')

@section('title', 'Curso' . $curso->name)

@section('content')
  <h1>Bienvenido al curso {{ $curso->name }}</h1>
  <a href="{{ route('cursos.index') }}">Volver a cursos</a>
  <br>

  <a href="{{ route('cursos.edit', $curso) }}">Editar curso</a>

  <p><strong>Categoria: </strong>{{ $curso->categoria }}</p>
  <p><strong>Descripción del curso: </strong>{{ $curso->descripcion }}</p>

  <form action="{{ route('cursos.destroy', $curso) }}" method="POST">
    @csrf
    @method('delete')
    <button type="submit">Eliminar</button>
  </form>
@endsection

resources/views/home.blade.php
@extends('layaouts.layaout')

@section('title', 'Home')

@section('content')
	<h1>Bienvenido a la página principal</h1>
@endsection

resources/views/layaouts/layaout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>@yield('title')</title> {{-- La propiedad yield hará que el contenido sea variable en cada página --}}
  <!-- favicon -->
  <!-- estilos -->
  <style>
    * {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif
    }

    .active {
      color: red;
      font-weight: bold;
    }
  </style>
</head>
<body>
  @include('layaouts.partials.header')
  @yield('content')

  <!-- footer -->
  @include('layaouts.partials.footer')
</body>
</html>

resources/views/layaouts/partials/footer.blade.php
<footer>
  Este es el pie de página
</footer>

resources/views/layaouts/partials/header.blade.php
<header>
  <h1>Inicio</h1>
  <nav>
    <ul>
      <li><a href="{{ route('home') }}" class="{{ request()->routeIs('home') ? 'active' : '' }}">Home</a></li>
      <li><a href="{{ route('cursos.index') }}" class="{{ request()->routeIs('cursos.*') ? 'active' : '' }}">Cursos</a></li>
      <li><a href="{{ route('nosotros') }}" class="{{ request()->routeIs('nosotros') ? 'active' : '' }}">Nosotros</a></li>

      <li><a href="{{ route('contacto.index') }}" class="{{ request()->routeIs('contacto.index') ? 'active' : '' }}">Contáctanos</a></li>
    </ul>
  </nav>
</header>

resources/views/nosotros.blade.php
@extends('layaouts.layaout')

@section('title', 'Nosotros')

@section('content')
  <h1>Nosotros</h1>
@endsection